'use client';

import React, { useState } from 'react';
import { FileText, Copy, Download, Check, BookOpen, Terminal, Layers, Server } from 'lucide-react';

interface DocItem {
  id?: number;
  title: string;
  content: string;
}

export const DocumentationTab: React.FC<{ docs: Record<string, DocItem> }> = ({ docs }) => {
  const [activeDocKey, setActiveDocKey] = useState<string>('readme');
  const [copied, setCopied] = useState(false);

  const docTypes = [
    { key: 'readme', label: 'README.md', icon: BookOpen },
    { key: 'install', label: 'Installation Guide', icon: Terminal },
    { key: 'architecture', label: 'Architecture Spec', icon: Layers },
    { key: 'api', label: 'API Specification', icon: Server },
    { key: 'deployment', label: 'Deployment Guide', icon: FileText },
  ];

  const currentDoc = docs[activeDocKey] || {
    title: 'Generated Documentation',
    content: '# Documentation\n\nGenerated auto documentation content.',
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(currentDoc.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([currentDoc.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${activeDocKey}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-purple-400" />
            Auto-Generated Project Documentation
          </h3>
          <p className="text-xs text-slate-400">
            Missing documentation generated by the LangGraph Documentation Agent.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="px-3.5 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 text-xs font-medium flex items-center gap-1.5 transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy Markdown'}
          </button>
          <button
            onClick={handleDownload}
            className="px-3.5 py-1.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-medium flex items-center gap-1.5 transition-all shadow-md shadow-purple-600/20"
          >
            <Download className="w-3.5 h-3.5" />
            Download .md
          </button>
        </div>
      </div>

      {/* Doc Navigation Tabs */}
      <div className="flex flex-wrap gap-2 border-b border-white/10 pb-3">
        {docTypes.map((dt) => {
          const Icon = dt.icon;
          const isActive = activeDocKey === dt.key;
          return (
            <button
              key={dt.key}
              onClick={() => setActiveDocKey(dt.key)}
              className={`px-4 py-2 rounded-xl text-xs font-medium transition-all flex items-center gap-2 ${
                isActive
                  ? 'bg-purple-600/30 text-purple-300 border border-purple-500/40 shadow-sm'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-white/5'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              {dt.label}
            </button>
          );
        })}
      </div>

      {/* Markdown Content Viewer */}
      <div className="glass-card rounded-2xl p-6 border border-white/10 bg-slate-950/80 font-mono text-sm leading-relaxed overflow-x-auto text-slate-300 whitespace-pre-wrap min-h-[400px]">
        {currentDoc.content}
      </div>
    </div>
  );
};
