'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Calendar, CheckSquare, Square, Clock, AlertTriangle, FileCode, ArrowRight } from 'lucide-react';
import { toggleTaskStatus } from '@/lib/api';

interface TaskItem {
  id: number;
  week: number;
  title: string;
  description: string;
  priority: string;
  estimated_hours: number;
  difficulty: string;
  target_files: string[];
  dependencies: string[];
  is_completed: boolean;
}

export const RoadmapTab: React.FC<{ tasks: TaskItem[]; onTaskUpdated: () => void }> = ({ tasks, onTaskUpdated }) => {
  const weeks = [1, 2, 3, 4];

  const handleToggle = async (taskId: number) => {
    try {
      await toggleTaskStatus(taskId);
      onTaskUpdated();
    } catch (e) {
      console.error("Failed to toggle task", e);
    }
  };

  const getPriorityBadge = (priority: string) => {
    switch (priority) {
      case 'High':
        return <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-rose-500/10 text-rose-400 border border-rose-500/30">High Priority</span>;
      case 'Medium':
        return <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/30">Medium Priority</span>;
      default:
        return <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-slate-500/10 text-slate-400 border border-slate-500/30">Low Priority</span>;
    }
  };

  return (
    <div className="space-y-8">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Calendar className="w-5 h-5 text-purple-400" />
          4-Week AI Recovery Roadmap
        </h3>
        <p className="text-xs text-slate-400">
          Prioritized milestone checklist generated by the Roadmap Agent to bring the repository to full health.
        </p>
      </div>

      <div className="space-y-6">
        {weeks.map((weekNum) => {
          const weekTasks = tasks.filter((t) => t.week === weekNum);
          if (weekTasks.length === 0) return null;

          return (
            <div key={weekNum} className="glass-card rounded-2xl p-6 border border-white/10 space-y-4">
              <div className="flex items-center justify-between border-b border-white/10 pb-3">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-purple-600/20 text-purple-300 font-extrabold flex items-center justify-center border border-purple-500/30 font-mono">
                    W{weekNum}
                  </div>
                  <h4 className="text-base font-bold text-white">
                    Week {weekNum}: Milestone Phase
                  </h4>
                </div>
                <div className="text-xs text-slate-400 font-mono">
                  {weekTasks.filter((t) => t.is_completed).length} / {weekTasks.length} Completed
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {weekTasks.map((task) => (
                  <motion.div
                    key={task.id}
                    whileHover={{ scale: 1.01 }}
                    className={`p-4 rounded-xl border transition-all flex flex-col justify-between space-y-3 ${
                      task.is_completed
                        ? 'bg-emerald-950/20 border-emerald-500/30 opacity-80'
                        : 'bg-slate-900/60 border-white/10 hover:border-purple-500/30'
                    }`}
                  >
                    <div className="space-y-2">
                      <div className="flex items-start justify-between gap-2">
                        <button
                          onClick={() => handleToggle(task.id)}
                          className="flex items-center gap-2.5 text-left text-sm font-bold text-white hover:text-purple-300 transition-colors"
                        >
                          {task.is_completed ? (
                            <CheckSquare className="w-5 h-5 text-emerald-400 shrink-0" />
                          ) : (
                            <Square className="w-5 h-5 text-slate-500 shrink-0" />
                          )}
                          <span className={task.is_completed ? 'line-through text-slate-400' : ''}>
                            {task.title}
                          </span>
                        </button>
                        {getPriorityBadge(task.priority)}
                      </div>
                      <p className="text-xs text-slate-300 pl-7 leading-relaxed">
                        {task.description}
                      </p>
                    </div>

                    <div className="pt-2 border-t border-white/5 pl-7 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-400">
                      <div className="flex items-center gap-3">
                        <span className="flex items-center gap-1 font-mono text-[11px]">
                          <Clock className="w-3.5 h-3.5 text-cyan-400" />
                          {task.estimated_hours} hrs
                        </span>
                        <span className="font-mono text-[11px] px-2 py-0.5 rounded bg-white/5 border border-white/10">
                          {task.difficulty}
                        </span>
                      </div>
                      {task.target_files && task.target_files.length > 0 && (
                        <div className="flex items-center gap-1 font-mono text-[10px] text-purple-300">
                          <FileCode className="w-3 h-3" />
                          {task.target_files[0]}
                        </div>
                      )}
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
