from typing import Dict, Any

class DocAgent:
    """Agent responsible for auto-generating missing repository documentation."""

    @staticmethod
    def generate_all(repo_name: str, intel: Dict[str, Any]) -> Dict[str, str]:
        is_empty = intel.get("is_empty", False)
        framework = intel.get("framework", "Application")
        primary_lang = intel.get("primary_language", "Codebase")
        database = intel.get("database", "None detected")
        auth = intel.get("auth", "None detected")
        tech_stack = intel.get("tech_stack", [primary_lang, framework])
        stack_str = ", ".join(tech_stack)
        top_dirs = intel.get("top_dirs", [])
        owner = intel.get("owner", "owner")

        # Determine appropriate installation commands
        lang_lower = primary_lang.lower()
        if is_empty:
            install_cmd = f"# Repository is empty. Initialize project:\n# mkdir {repo_name} && cd {repo_name}"
            run_cmd = "# Add source files and entry point"
        elif lang_lower in ("typescript", "javascript"):
            install_cmd = "npm install"
            run_cmd = "npm run dev"
        elif lang_lower == "python":
            install_cmd = "pip install -r requirements.txt"
            run_cmd = "python main.py"
        elif lang_lower == "go":
            install_cmd = "go mod download"
            run_cmd = "go run main.go"
        elif lang_lower == "rust":
            install_cmd = "cargo build"
            run_cmd = "cargo run"
        elif lang_lower in ("c", "c++"):
            install_cmd = "cmake -B build"
            run_cmd = "cmake --build build"
        else:
            install_cmd = "# Install dependencies for " + primary_lang
            run_cmd = "# Run project entrypoint"

        dirs_markdown = "\n".join([f"- `{d}/` - Source module container" for d in top_dirs[:6]]) if top_dirs else "- `(Root)` - Single file or initial repo root"

        readme = f"""# {repo_name}

> Repository specification & recovery blueprint generated by **Revive AI**.

## 🚀 Overview

**{repo_name}** is a **{primary_lang}** application built using **{framework}**.

### Tech Stack
- **Primary Language**: {primary_lang}
- **Framework / Core**: {framework}
- **Data Persistence**: {database}
- **Authentication**: {auth}
- **Detected Tags**: {stack_str}

---

## 🛠️ Quick Start

```bash
# Clone the repository
git clone https://github.com/{owner}/{repo_name}.git
cd {repo_name}

# Install dependencies
{install_cmd}

# Run application
{run_cmd}
```

---

## 🗺️ Project Structure

{dirs_markdown}
- `docs/` - System architecture and specification guides.
"""

        install_guide = f"""# Installation & Setup Guide for {repo_name}

## Environment Requirements
- Primary Toolchain: **{primary_lang}**
- Framework: **{framework}**
- Persistence Layer: **{database}**

## Step-by-Step Instructions

1. **Clone Repository**:
   ```bash
   git clone https://github.com/{owner}/{repo_name}.git
   cd {repo_name}
   ```

2. **Environment Configuration**:
   Create local environment file if `.env.example` exists:
   ```bash
   cp .env.example .env 2>/dev/null || touch .env
   ```

3. **Install Dependencies**:
   ```bash
   {install_cmd}
   ```

4. **Run Development Server**:
   ```bash
   {run_cmd}
   ```
"""

        arch_doc = f"""# Architecture & Engineering Guide for {repo_name}

## System Overview
The **{repo_name}** codebase is structured around a **{framework}** architecture utilizing **{primary_lang}**.

1. **Core Service Engine**: Handled via `{framework}` routines.
2. **Data & Storage Layer**: `{database}` interface layer.
3. **Identity & Access**: `{auth}` flow.

## AI Recovery Engine Assessment
- **Primary Language**: {primary_lang}
- **File Count**: {intel.get('file_count', 0)} files
- **Staleness**: {intel.get('days_since_commit', 0)} days since last commit
"""

        api_doc = f"""# API & Interface Documentation

## {repo_name} Public Interface Specification

### Core Endpoints / Public Modules
- **Primary Framework**: {framework}
- **Authentication Handler**: {auth}
- **Data Layer**: {database}

### Status & Health Verification
Use standard build/test commands to verify endpoint integrity.
"""

        deploy_guide = f"""# Deployment Guide for {repo_name}

## Deployment Architecture
1. Containerize application using Docker (if Dockerfile present) or standard runtime build scripts.
2. Configure environment variables for **{database}** and **{auth}**.
3. Deploy build output to target cloud infrastructure (e.g. Vercel, Railway, AWS, or Docker host).
"""

        return {
            "readme": readme,
            "install": install_guide,
            "architecture": arch_doc,
            "api": api_doc,
            "deployment": deploy_guide
        }

